spring:
  cloud:
    gateway:
      httpclient:
          connect-timeout: 5000
          response-timeout: 5000
      routes:
        - id: user-service
          uri: http://localhost:9090
          predicates:
            - Path=/user/**
        - id: menu-service
          uri: http://localhost:9090
          predicates:
            - Path=/menu/**
  main:
    web-application-type: reactive
