CREATE TABLE JG_USER_MTB (
ID INT (10) AUTO_INCREMENT NOT NULL,
FIRST_NAME VARCHAR (50),
LAST_NAME VARCHAR (50),
USER_GROUP VARCHAR (20),
PRIMARY KEY (ID)
);

CREATE TABLE JG_MENU_MTB (
ID INT (10) AUTO_INCREMENT NOT NULL,
MENU_CODE VARCHAR (20),
MENU_NAME VARCHAR (100),
MENU_GROUP VARCHAR(20),
PRIMARY KEY (ID)
);
